/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { App } from "./App";
export * as factories from "./factories";
export { App__factory } from "./factories/App__factory";
